[build]
  command = "npm run build" # Specify the build command for your React front-end
  publish = "dist" # Specify the directory where the built React app will be published

[[plugins]]
  package = "@netlify/plugin-functions-core" # Required for deploying serverless functions

[[plugins]]
  package = "@netlify/plugin-functions-install" # Required for installing Python dependencies

[[plugins]]
  package = "@netlify/plugin-cache" # Optional: Enables caching to speed up builds

[[plugins]]
  package = "@netlify/plugin-nextjs" # Optional: If using Next.js for your React front-end